import {
  BASE_SENSORS,
  PILOT_SCOPE_ID,
} from '../data/indorePilotData';
import {
  DataEnvelope,
  DataProvenance,
  ProductMode,
  ScenarioParameters,
  SensorNode,
} from '../types/idhara';

/**
 * Generates deterministic provenance metadata for any entity or API envelope.
 * Never claims simulated or mock data is real live municipal telemetry.
 */
export function createProvenance(
  mode: ProductMode,
  confidence: number,
  timelineHourOffset: number = 0
): DataProvenance {
  const baseAnchor = new Date('2026-10-07T14:30:00.000Z');
  const offsetMs = timelineHourOffset * 3600 * 1000;
  const generatedDate = new Date(baseAnchor.getTime() + offsetMs);
  const dataAsOfDate = new Date(generatedDate.getTime() - 90 * 1000); // 90s ingestion lag

  return {
    mode,
    scope_id: PILOT_SCOPE_ID,
    generated_at: generatedDate.toISOString(),
    data_as_of: dataAsOfDate.toISOString(),
    confidence: Number(Math.max(0.15, Math.min(0.98, confidence)).toFixed(2)),
  };
}

export function wrapInEnvelope<T>(
  payload: T,
  mode: ProductMode,
  confidence: number,
  timelineHourOffset: number = 0
): DataEnvelope<T> {
  const prov = createProvenance(mode, confidence, timelineHourOffset);
  const modeDisclaimers: Record<ProductMode, string> = {
    [ProductMode.SIMULATED]:
      'SIMULATED MODE: Outputs are generated by the iDhara hydrological-terrain proxy engine using synthetic Indore 5×5 km pilot parameters.',
    [ProductMode.HISTORICAL]:
      'HISTORICAL REPLAY MODE: Reconstructed from archived Indore monsoon cloudburst profiles and high-water mark surveys.',
    [ProductMode.MOCK]:
      'MOCK BENCHMARK MODE: Deterministic stress-test dataset for validating control-room workflows and shelter capacity.',
    [ProductMode.LIVE]:
      'LIVE PILOT STREAM (SYNTHETIC TELEMETRY): Connected to simulated real-time sensor ingestion loop for the Indore 5×5 km pilot zone; not official government broadcast data.',
  };

  return {
    ...prov,
    payload,
    disclaimer: modeDisclaimers[mode],
  };
}

/**
 * Synthesizes sensor readings across the 10 Indore pilot gauges based on current scenario parameters.
 */
export function ingestSensorTelemetry(params: ScenarioParameters): SensorNode[] {
  const rainFactor = params.rainfallIntensityMmHr / 50;
  const blockageFactor = params.drainageBlockagePct / 40;
  const inflowFactor = params.upstreamKahnInflowMultiplier;

  return BASE_SENSORS.map((s, idx) => {
    const isDroppedOut = idx >= BASE_SENSORS.length - params.sensorDropoutCount;
    const isDrifting = !isDroppedOut && idx === 3 && params.drainageBlockagePct > 45;

    let currentValue = s.baseValue;
    if (s.type === 'RAIN_GAUGE') {
      // Spatial micro-variation across the 5x5 km catchment
      const spatialMultiplier = 0.92 + ((idx % 3) * 0.07);
      currentValue = Number((params.rainfallIntensityMmHr * spatialMultiplier).toFixed(1));
    } else if (s.type === 'WATER_LEVEL_ULTRASONIC') {
      const surge =
        (s.baseValue * 0.55 * rainFactor) +
        (s.baseValue * 0.28 * blockageFactor) +
        (s.baseValue * 0.22 * (inflowFactor - 1));
      currentValue = Number(Math.max(0.1, s.baseValue * 0.5 + surge).toFixed(2));
    } else if (s.type === 'FLOW_DISCHARGE') {
      currentValue = Number(
        Math.round(s.baseValue * (0.45 + 0.55 * rainFactor) * inflowFactor)
      );
    }

    let status: SensorNode['status'] = 'NOMINAL';
    if (isDroppedOut) {
      status = 'STALE';
    } else if (currentValue >= s.criticalThreshold) {
      status = 'CRITICAL_THRESHOLD';
    } else if (isDrifting || currentValue >= s.warningThreshold) {
      status = 'DRIFTING';
    }

    const lastHeartbeatSecAgo = isDroppedOut ? 1420 : 18 + (idx * 7) % 45;
    const sensorConfidence = isDroppedOut ? 0.42 : isDrifting ? 0.74 : 0.93;
    const prov = createProvenance(params.mode, sensorConfidence, params.timelineHourOffset);

    return {
      ...prov,
      id: s.id,
      name: s.name,
      type: s.type,
      x: s.x,
      y: s.y,
      lat: s.lat,
      lng: s.lng,
      cellId: s.cellId,
      currentValue,
      unit: s.unit,
      warningThreshold: s.warningThreshold,
      criticalThreshold: s.criticalThreshold,
      status,
      lastHeartbeatSecAgo,
      batteryPct: 82 + ((idx * 5) % 17),
      packetSuccessRatePct: isDroppedOut ? 48.5 : isDrifting ? 86.2 : 99.1,
    };
  });
}
